-- MySQL Script generated by MySQL Workbench
-- Mon May 12 15:33:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
                                                `idUsuario` INT NOT NULL AUTO_INCREMENT,
                                                `musica` VARCHAR(45) NULL,
    `email` VARCHAR(100) NULL,
    `senha` VARCHAR(45) NULL,
    `composi` LONGTEXT NULL,
    `data_nascimento` DATE NULL,
    `bio` VARCHAR(45) NULL,
    `foto` VARCHAR(45) NULL,
    `tipo_usuario` VARCHAR(45) NULL,
    `data_criacao` DATE NULL,
    `status_online` VARCHAR(45) NULL DEFAULT '(\'online\', \'offline\') default \'offline\'',
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amigos` (
                                               `Usuario_idUsuario` INT NOT NULL,
                                               `idAmigo` INT NOT NULL,
                                               `status` VARCHAR(45) NULL,
    `data_inicio` INT NULL,
    PRIMARY KEY (`Usuario_idUsuario`, `idAmigo`),
    CONSTRAINT `fk_amigos_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
